version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/app/uploads
    network_mode: "host"  # Required for printer discovery