services:
  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://printapi.borklab.com
    networks:
      - netprint-network

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - netprint-network

networks:
  netprint-network:
    driver: bridge