services:
  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://printapi.borklab.com
    networks:
      - netprint-network

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    network_mode: "host"  # Use host network for printer discovery
    volumes:
      - ./uploads:/app/uploads

networks:
  netprint-network:
    driver: bridge